"""
evaluate.py - Model Evaluation and Reporting Utilities
========================================================

Generates structured evaluation reports in Markdown format
and prints summary tables to the console.

Usage
-----
>>> from src.evaluate import generate_report, print_summary
>>> report = generate_report(results)
>>> print_summary(results)
"""

from __future__ import annotations

import logging
from typing import Any, Dict

import numpy as np

logger = logging.getLogger(__name__)


def generate_report(results: Dict[str, Any]) -> str:
    """Generate a Markdown evaluation report from model results.

    Parameters
    ----------
    results : dict
        Dictionary containing 'classification' and optionally
        'regression' and 'feature_importances' keys.

    Returns
    -------
    str
        Markdown-formatted report string.
    """
    lines = [
        "# IPL Match Predictor - Evaluation Report",
        "",
        "## Classification: Match Winner Prediction",
        "",
    ]

    clf = results.get("classification", {})
    if clf:
        lines.extend([
            f"- **Accuracy**: {clf.get('accuracy', 0):.4f}",
            f"- **F1 Score (weighted)**: {clf.get('f1', 0):.4f}",
            "",
        ])

        # Confusion matrix
        cm = clf.get("confusion_matrix")
        if cm is not None:
            lines.extend([
                "### Confusion Matrix",
                "",
                "```",
                "                 Predicted",
                "              Team2  Team1",
                f"Actual Team2   {cm[0][0]:4d}   {cm[0][1]:4d}",
                f"Actual Team1   {cm[1][0]:4d}   {cm[1][1]:4d}",
                "```",
                "",
            ])

        # Classification report
        report = clf.get("report", {})
        if report:
            lines.extend([
                "### Per-Class Metrics",
                "",
                "| Class | Precision | Recall | F1 |",
                "|-------|-----------|--------|-----|",
            ])
            for cls_name in ["Team 2 Wins/Other", "Team 1 Wins"]:
                cls_metrics = report.get(cls_name, {})
                if cls_metrics:
                    lines.append(
                        f"| {cls_name} | "
                        f"{cls_metrics.get('precision', 0):.3f} | "
                        f"{cls_metrics.get('recall', 0):.3f} | "
                        f"{cls_metrics.get('f1-score', 0):.3f} |"
                    )
            lines.append("")

    # Feature importances
    fi = results.get("feature_importances")
    if fi is not None and len(fi) > 0:
        lines.extend([
            "## Top Feature Importances",
            "",
            "| Rank | Feature | Importance |",
            "|------|---------|------------|",
        ])
        for i, row in fi.head(10).iterrows():
            lines.append(f"| {i + 1} | {row['Feature']} | {row['Importance']:.4f} |")
        lines.append("")

    # Regression
    reg = results.get("regression", {})
    if reg and "note" not in reg:
        lines.extend([
            "## Regression: Run Margin Prediction",
            "",
            f"- **MAE**: {reg.get('mae', 0):.4f}",
            f"- **RMSE**: {reg.get('rmse', 0):.4f}",
            f"- **R2 Score**: {reg.get('r2', 0):.4f}",
            "",
        ])

    lines.extend([
        "---",
        "",
        "*Report generated by IPL Match Predictor pipeline*",
    ])

    return "\n".join(lines)


def print_summary(results: Dict[str, Any]) -> None:
    """Print a concise summary of model evaluation results.

    Parameters
    ----------
    results : dict
        Dictionary containing model evaluation metrics.
    """
    print("\n" + "=" * 50)
    print("  IPL Match Predictor - Results Summary")
    print("=" * 50)

    clf = results.get("classification", {})
    if clf:
        print(f"\n  Classification (Match Winner)")
        print(f"  {'Accuracy:':<20} {clf.get('accuracy', 0):.4f}")
        print(f"  {'F1 (weighted):':<20} {clf.get('f1', 0):.4f}")

    fi = results.get("feature_importances")
    if fi is not None and len(fi) > 0:
        print(f"\n  Top 5 Features:")
        for i, row in fi.head(5).iterrows():
            print(f"    {i + 1}. {row['Feature']:<30} {row['Importance']:.4f}")

    reg = results.get("regression", {})
    if reg and "note" not in reg:
        print(f"\n  Regression (Run Margin)")
        print(f"  {'MAE:':<20} {reg.get('mae', 0):.4f}")
        print(f"  {'RMSE:':<20} {reg.get('rmse', 0):.4f}")
        print(f"  {'R2:':<20} {reg.get('r2', 0):.4f}")

    print("\n" + "=" * 50)